---
title: 'Case Study 9: Hurricanes'
author: "Betsy McCall"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
library(kableExtra)
library(raster)
library(ggplot2)

dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
```

## Atlantic Hurricane Data by decade, since 1950

The top section loads libraries and the data into our document.  Then we'll build our map and table from it.



```{r processing, echo=FALSE, message=FALSE, warning=FALSE}
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))

#filter and make decades
storm_data_mod <- storm_data %>% filter(SEASON>=1950) %>% mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))
storm_mod_dec <- storm_data_mod %>% mutate(decade=(floor(year/10)*10))

us_states_match <- us_states %>% st_transform(crs(storm_mod_dec)) %>% rename(state=NAME)

#find bounding box
region <- st_bbox(storm_mod_dec)
xlims <- c(region[1],region[3])
ylims <- c(region[2],region[4])

working <- st_join(storm_mod_dec, us_states_match, join=st_intersects, left=FALSE)

```

## Pretty pictures

```{r plot, echo=FALSE, message=FALSE, warning=FALSE}
plot1 <- ggplot(data = world) +geom_sf(color = "gray40", fill = "honeydew2") +
  stat_bin2d(data=storm_mod_dec, aes(y=st_coordinates(storm_mod_dec)[,2],x=st_coordinates(storm_mod_dec)[,1]),bins=100) + 
  coord_sf(xlim=xlims, ylim=ylims, expand = FALSE) + scale_fill_distiller(palette="YlOrRd",trans="log",direction=-1, breaks=c(1,10,100,1000))
#plot1

plot2 <- plot1 + facet_wrap(~decade) + theme(axis.title.x=element_blank(),axis.title.y=element_blank())
#x11()
plot2
```

## Table of states with the most hurricanes


```{r table, echo=FALSE, message=FALSE, warning=FALSE}
working %>% group_by(state) %>% summarize(storms=length(unique(NAME))) %>% 
  arrange(desc(storms)) %>% slice(1:5) %>% st_set_geometry(NULL) %>% knitr::kable(format="simple")

```

